export const END_POINT = {
  EXAMPLE: "/api/example",
  MY_INFO: "/api/users/me",
  BOOTCAMPS: "/api/bootcamps",
  MY_REVIEWS: "/api/reviews/my",
  POINT_HISTORY: "api/points/me",
  MENTOR_LIST: "/api/coffee-chats/info/search",
  APPROVED_COFFEE_CHATS: "/api/coffee-chats/applications/approved",
  FILE_UPLOAD: "/api/file/upload",
  SENT_COFFEE_CHATS: "/api/coffee-chats/applications",
  RECEIVED_COFFEE_CHATS: "/api/coffee-chats/received",
  BOOTCAMP_DETAIL: (id: string) => `/bootcamps/${id}`,
  REVIEWS: "/api/reviews",
  MENTOR_INFO: "/api/coffee-chats/info/user-info",
  MENTOR_TIME: "/api/coffee-chats/times/available-times",
  MENTOR_APPLICATION_TIME: "/api/coffee-chats/times/{mentorId}",
  CHAT_ROOM: (roomUuid: string) => `/chat-rooms/${roomUuid}`,
  CHAT_ROOM_LIST: "/api/chat-rooms",
} as const;
